### ISSUE TITLE
Weaving fails

### ISSUE THREAD

**Issue by dittodhole** [dittodhole/csharp-SemVer.Fody#2]
> 1>    Fody: Fody (version 1.29.4.0) Executing
> 1>MSBUILD : error : Fody: An unhandled exception occurred:
> 1>MSBUILD : error : Exception:
> 1>MSBUILD : error : The method 'SemVer.Fody.ModuleWeaverBase.set_LogError' is not a property accessor
> 1>MSBUILD : error : StackTrace:
> 1>MSBUILD : error :    at System.Linq.Expressions.Expression.GetProperty(MethodInfo mi)
> 1>MSBUILD : error :    at System.Linq.Expressions.Expression.Property(Expression expression, MethodInfo propertyAccessor)
> 1>MSBUILD : error :    at PropertyDelegateBuilder.TryBuildPropertySetDelegate[T](Type targetType, String propertyName, Action`2& action) in C:\projects\fody\FodyIsolated\DelegateBuilders\PropertyDelegateBuilder.cs:line 24
> 1>MSBUILD : error :    at DelegateBuilder.BuildDelegateHolder(Type weaverType) in C:\projects\fody\FodyIsolated\DelegateBuilders\DelegateBuilder.cs:line 31
> 1>MSBUILD : error :    at DelegateBuilder.GetDelegateHolderFromCache(Type weaverType) in C:\projects\fody\FodyIsolated\DelegateBuilders\DelegateBuilder.cs:line 15
> 1>MSBUILD : error :    at InnerWeaver.InitialiseWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 120
> 1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 81
> 1>MSBUILD : error : Source:
> 1>MSBUILD : error : System.Core
> 1>MSBUILD : error : TargetSite:
> 1>MSBUILD : error : System.Reflection.PropertyInfo GetProperty(System.Reflection.MethodInfo)
> 1>MSBUILD : error : 
> 1>    Fody:   Finished Fody 229ms.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
>

**Comment by dittodhole** [comment]
see 862efdc14b2ac42469d1fbc7a387d80230b73ac2

**Comment by dittodhole** [comment]
still there
