### ISSUE TITLE
Weaving fails: "Could not load Sharp2Svn"

### ISSUE THREAD

**Issue by dittodhole** [dittodhole/csharp-SemVer.Fody#5]
> 1>      Fody/SemVer.Svn:   Starting search for repository in ProjectDir
> 1>MSBUILD : warning : Fody/SemVer.Svn: Failed to load 'W:\work\ImtechCommon\trunk\packages\src\cargonet.Broadcast\trunk\Packages\SemVer.Svn.Fody.1.0.0-alpha8\SharpSvn.dll'. Going to swallow and continue to let other AssemblyResolve events to attempt to resolve. Exception:System.IO.FileLoadException: Could not load file or assembly 'SharpSvn, Version=1.9003.3799.86, Culture=neutral, PublicKeyToken=d729672594885a28' or one of its dependencies. Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019)
> 1>MSBUILD : warning : File name: 'SharpSvn, Version=1.9003.3799.86, Culture=neutral, PublicKeyToken=d729672594885a28' ---> System.IO.FileLoadException: Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019)
> 1>MSBUILD : warning :    at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, SecurityContextSource securityContextSource)
> 1>MSBUILD : warning :    at System.Reflection.Assembly.Load(Byte[] rawAssembly)
> 1>MSBUILD : warning :    at InnerWeaver.LoadFromFile(String assemblyPath) in C:\projects\fody\FodyIsolated\AssemblyLoader.cs:line 35
> 1>MSBUILD : warning :    at InnerWeaver.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args) in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 50
> 1>MSBUILD : warning : 
> 1>MSBUILD : warning : 
> 1>MSBUILD : error : Fody: An unhandled exception occurred:
> 1>MSBUILD : error : Exception:
> 1>MSBUILD : error : Could not load file or assembly 'SharpSvn, Version=1.9003.3799.86, Culture=neutral, PublicKeyToken=d729672594885a28' or one of its dependencies. The system cannot find the file specified.
> 1>MSBUILD : error : StackTrace:
> 1>MSBUILD : error :    at SemVer.Fody.ModuleWeaver.GetVersion(String repositoryPath, String patchFormat, String featureFormat, String breakingChangeFormat)
> 1>MSBUILD : error :    at SemVer.Fody.ModuleWeaver.PatchVersionOfAssemblyTheSemVerWay(XElement config, String assemblyFullFileName, String addinDirectoryPath, String solutionPath, String projectPath)
> 1>MSBUILD : error :    at SemVer.Fody.ModuleWeaver.AfterWeaving()
> 1>MSBUILD : error :    at lambda_method(Closure , Object )
> 1>MSBUILD : error :    at InnerWeaver.ExecuteAfterWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 187
> 1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 86
> 1>MSBUILD : error : Source:
> 1>MSBUILD : error : SemVer.Svn.Fody
> 1>MSBUILD : error : TargetSite:
> 1>MSBUILD : error : System.Version GetVersion(System.String, System.String, System.String, System.String)
> 1>MSBUILD : error : 
> 1>    Fody:   Finished Fody 510ms.
>

**Comment by dittodhole** [comment]
refs 40d9f0a
